# Generated by Django 5.1.4 on 2025-01-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('school_name', models.CharField(max_length=100)),
                ('english_certificate', models.CharField(blank=True, choices=[('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('CEFR', 'CEFR'), ('Other', 'Other')], max_length=50, null=True)),
                ('english_certificate_score', models.CharField(blank=True, max_length=30, null=True)),
                ('sat_score', models.CharField(blank=True, max_length=10, null=True)),
                ('passport', models.FileField(upload_to='documents/passports/')),
                ('language_certificate', models.FileField(upload_to='documents/language_certificates/')),
                ('sat_certificate', models.FileField(blank=True, null=True, upload_to='documents/sat_certificates/')),
                ('photo', models.FileField(upload_to='documents/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_of_birth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='birth_country_admissions', to='admission.country')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nationality_admissions', to='admission.country')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admission.program')),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
            },
        ),
    ]
