version: "3.8"

services:
  # PostgreSQL service
  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:16  # Using PostgreSQL 16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - 5434:5432  # Mapping PostgreSQL port
    restart: always

  # Django backend service
  web: &web
    container_name: ${PROJECT_NAME}_backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "cd turin_qabul && chmod +x ./entrypoint.dev.sh && ./entrypoint.dev.sh && gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./:/app
      - ./requirements:/home/app/web/requirements
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
    ports:
      - 8000:8000  # Exposing Django app on port 8000
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
